/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * Attempts to read a vector of Reminders from the specified path. Returns a result containing a Vector of Reminders.
 */
export function readAllReminders(path: string) {
    return invoke()<Reminder[]>("read_all_reminders", { path })
}

export function getPath() {
    return invoke()<string>("get_path")
}

/**
 * Attempts to modify an existing `Reminder` by name with an `EditReminder`.
 * Returns a result containing the number of changes, i.e. 0 means no edits were made.
 * Currently multiple edits are not implemented nor tested.
 */
export function editReminder(path: string, name: string, newData: EditReminder) {
    return invoke()<number>("edit_reminder", { path,name,newData })
}

export type EditReminder = { name: string | null; description: string | null; frequency: number | null; icon: string | null }
/**
 * Struct to represent a reminder.
 */
export type Reminder = { name: string; description: string; frequency: number; icon: string | null }
