[[reminders]]
name = "Drink some water!"
icon = "💧"
description = "Make sure to stay hydrated!"
frequency = 5

[[reminders]]
name = "Stretch!"
description = "Make sure to get up and stretch for a few minutes! It's good for you."
frequency = 10

[[reminders]]
name = "Str!"
description = "Mak! It's good for you."
frequency = 50
